[en]
title = "Ruixi's Blog"
languageName = "English"
languageCode = "en"

[en.params.homeInfoParams]
Title = "Hi there. ğŸ‘‹"
Content = "This is Ruixi's cozy corner on the web."

[[en.params.socialIcons]]
name = "Github"
title = "Github"
icon = "Github"
url = "https://github.com/Ruixi-Cheng/"
[[en.params.socialIcons]]
name = "Bilibili"
title = "Bilibili"
icon = "Bilibili"
url = "https://space.bilibili.com/329971737"

[zh]
title = "Ruixi çš„åšå®¢"
languageName = "ä¸­æ–‡"
languageCode = "zh"

[zh.params.homeInfoParams]
Title = "ä½ å¥½ ğŸ‘‹"
Content = "è¿™é‡Œæ˜¯ Ruixi çš„å°ç«™ã€‚"


[[zh.params.socialIcons]]
name = "Github"
title = "Github"
icon = "Github"
url = "https://github.com/Ruixi-Cheng/"

[[zh.params.socialIcons]]
name = "Bilibili"
title = "Bilibili"
icon = "Bilibili"
url = "https://space.bilibili.com/329971737"

[ja]
title = "Ruixiã®ãƒ–ãƒ­ã‚°"
languageName = "æ—¥æœ¬èª"
languageCode = "ja"

[ja.params.homeInfoParams]
Title = "ä½ å¥½ ğŸ‘‹"
Content = "è¿™é‡Œæ˜¯ Ruixi çš„å°ç«™ã€‚"


[[ja.params.socialIcons]]
name = "Github"
title = "Github"
icon = "Github"
url = "https://github.com/Ruixi-Cheng/"

[[ja.params.socialIcons]]
name = "Bilibili"
title = "Bilibili"
icon = "Bilibili"
url = "https://space.bilibili.com/329971737"